trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies using npm ci'

- script: npm run build
  displayName: 'Build project (if needed)'
  continueOnError: true  # Use this only if you don’t have a build script

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/node-app.zip'
    replaceExistingArchive: true
  displayName: 'Archive project files'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<YOUR-AZURE-SERVICE-CONNECTION-NAME>'
    appType: 'webAppLinux'
    appName: '<YOUR-AZURE-WEBAPP-NAME>'
    runtimeStack: 'NODE|20-lts'
    package: '$(Build.ArtifactStagingDirectory)/node-app.zip'
  displayName: 'Deploy Node.js App to Azure Web App'
