# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

# variables:
#   API_TOKEN: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'
  
- script: npm install
  displayName: 'Install dependencies'  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Zip app files'  
- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web App'
  inputs:
    app_location: '/'
    api_location: 'api'
    output_location: 'dummy'
    # azure_static_web_apps_api_token: $(API_TOKEN)  

# - script: |
#     npm install
#   displayName: 'npm install only (no build)'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'


